import { z } from "zod";

export const scaffoldNodeInputSchema = {
	type: "object",
	properties: {
		description: {
			type: "string",
			description: "Plain-English description of what the node should do.",
		},
		nodeName: {
			type: "string",
			description:
				"Optional PascalCase node class name, e.g. 'DiscordRateLimited'. Derived from the description if omitted.",
		},
	},
	required: ["description"],
} as const;

const inputZod = z.object({
	description: z.string().min(1),
	nodeName: z
		.string()
		.regex(/^[A-Z][A-Za-z0-9]*$/, "nodeName must be PascalCase")
		.optional(),
});

export async function scaffoldNode(rawArgs: unknown) {
	const args = inputZod.parse(rawArgs);
	const nodeName = args.nodeName ?? deriveNodeName(args.description);
	const displayName = humanize(nodeName);
	const skeleton = renderSkeleton(nodeName, displayName, args.description);
	return {
		content: [{ type: "text" as const, text: skeleton }],
	};
}

function deriveNodeName(desc: string): string {
	const words = desc
		.split(/\W+/)
		.filter((w) => w.length > 0 && !STOPWORDS.has(w.toLowerCase()))
		.slice(0, 3)
		.map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase());
	const name = words.join("");
	return name.length > 0 ? name : "CustomNode";
}

const STOPWORDS = new Set([
	"a",
	"an",
	"the",
	"to",
	"that",
	"with",
	"and",
	"or",
	"of",
	"for",
	"from",
	"into",
	"node",
	"posts",
]);

function humanize(pascal: string): string {
	return pascal.replace(/([a-z])([A-Z])/g, "$1 $2");
}

function lowerFirst(s: string): string {
	return s.length === 0 ? s : s[0].toLowerCase() + s.slice(1);
}

function escapeSingle(s: string): string {
	return s.replace(/'/g, "\\'");
}

function renderSkeleton(
	nodeName: string,
	displayName: string,
	description: string,
): string {
	const safeBlockComment = description.replace(/\*\//g, "* /");
	const internalName = lowerFirst(nodeName);
	return `import {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	NodeOperationError,
} from 'n8n-workflow';

/**
 * ${safeBlockComment}
 *
 * Generated by @automatelab/n8n-mcp.
 */
export class ${nodeName} implements INodeType {
	description: INodeTypeDescription = {
		displayName: '${escapeSingle(displayName)}',
		name: '${internalName}',
		icon: 'file:icon.svg',
		group: ['transform'],
		version: 1,
		description: '${escapeSingle(description)}',
		defaults: {
			name: '${escapeSingle(displayName)}',
		},
		inputs: ['main'],
		outputs: ['main'],
		credentials: [
			{
				name: '${internalName}Api',
				required: true,
			},
		],
		properties: [
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				options: [
					{ name: 'Run', value: 'run' },
				],
				default: 'run',
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const returnData: INodeExecutionData[] = [];

		for (let i = 0; i < items.length; i++) {
			try {
				// TODO: implement '${escapeSingle(description)}'
				returnData.push({ json: items[i].json });
			} catch (error) {
				if (this.continueOnFail()) {
					returnData.push({ json: { error: (error as Error).message } });
					continue;
				}
				throw new NodeOperationError(this.getNode(), error as Error, { itemIndex: i });
			}
		}

		return [returnData];
	}
}
`;
}
